apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: di35x70py-python 
  janus-idp.io/tekton: di35x70py-python
  backstage.io/kubernetes-id: di35x70py-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: di35x70py-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml