apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: di35x70py-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: di35x70py-python 
  name: di35x70py-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: di35x70py-python
    weight: 100 
